// Generate samples.js from the two source markdown vocab files.
// Uses the same parsing logic as the app so built-in samples match imports.
// Usage: node gen_samples.mjs
import fs from "node:fs";

function stripMd(s){return String(s==null?"":s).replace(/\*\*(.+?)\*\*/g,"$1").replace(/`([^`]+)`/g,"$1").trim();}
const FRONT_KW=["english","英文","word","term","缩写","语句","句式","句子","phrase"];
const BACK_KW=["中文","释义","全称","meaning","translation","含义","解释","定义","definition"];
const EXAMPLE_KW=["例句","example","sentence","eg"];
const IGNORE_KW=["掌握","自填","备注","status","状态","count","数量","词条数","模块","module","说明","remark","level","note","progress"];
const isIndexHeader=c=>/^(no\.?|#|num\.?|index|序号|编号|序|id)$/i.test(c.trim());
function classifyColumns(headerCells){const h=headerCells.map(c=>c.toLowerCase().trim());const hit=(cell,kws)=>kws.some(k=>cell.includes(k));
  let front=-1,back=-1,example=-1;const ignore=new Set();
  h.forEach((c,i)=>{if(example<0&&hit(c,EXAMPLE_KW)){example=i;return;}if(front<0&&hit(c,FRONT_KW)){front=i;return;}
    if(back<0&&hit(c,BACK_KW)){back=i;return;}if(isIndexHeader(c)||hit(c,IGNORE_KW))ignore.add(i);});
  const recognized=front>=0||back>=0;
  if(front<0)front=firstFree([back,example],ignore,headerCells.length);
  if(back<0)back=firstFree([front,example],ignore,headerCells.length);
  if(example===front||example===back)example=-1;return{front,back,example,ignore,recognized};}
function firstFree(taken,ignore,len){for(let i=0;i<len;i++){if(taken.includes(i)||ignore.has(i))continue;return i;}return -1;}
function rowToEntry(cells,map,category){const get=i=>(i>=0&&i<cells.length?stripMd(cells[i]):"");const front=get(map.front);const example=get(map.example);const ignore=map.ignore||new Set();
  const backParts=[];if(map.back>=0)backParts.push(get(map.back));
  cells.forEach((c,i)=>{if(i===map.front||i===map.back||i===map.example||ignore.has(i))return;const v=stripMd(c);if(v)backParts.push(v);});
  const back=backParts.filter(Boolean).join(" / ");if(!front)return null;return{front,back,example,category};}
function parseMarkdown(text,defaultCat){const lines=text.split(/\r?\n/);const out=[];let category=defaultCat||"";let map=null;
  for(const line of lines){const heading=line.match(/^#{1,6}\s+(.+)$/);
    if(heading){category=stripMd(heading[1]).replace(/\s*[（(].*?[)）]\s*$/,"").trim()||category;map=null;continue;}
    if(!/\|/.test(line))continue;if(/^\s*\|?\s*:?-{2,}/.test(line.replace(/\s/g,"")))continue;
    const cells=line.replace(/^\s*\|/,"").replace(/\|\s*$/,"").split("|").map(c=>c.trim());
    if(cells.length<2)continue;if(!map){map=classifyColumns(cells);if(!map.recognized)map={skip:true};continue;}
    if(map.skip)continue;const entry=rowToEntry(cells,map,category||defaultCat||"未分类");if(entry)out.push(entry);}
  return out;}

const SOURCES = [
  { id: "brokerage-core", file: "../券商IT高频英语术语表.md", name: "券商IT高频术语表" },
  { id: "brokerage-2000", file: "../券商IT英语词汇表_2000.md", name: "券商IT英语词汇表（2000）" },
  { id: "trade-clear-asset", file: "../券商IT英语词汇表_交易清算资产.md", name: "交易/清算/资产（业务与系统）" },
  { id: "global-institutions", file: "../券商IT英语词汇表_交易所清算机构.md", name: "全球交易所与清算机构（专名缩写）" },
  { id: "meeting-email", file: "../券商IT英语词汇表_会议邮件句式.md", name: "会议沟通与邮件写作句式" },
  { id: "global-rules", file: "../券商IT英语词汇表_全球规则术语.md", name: "全球交易清算规则专有术语" },
  { id: "global-rules-real", file: "../券商IT英语词汇表_全球规则真实语料.md", name: "全球规则真实语料·术语（例句摘自原文）" },
  { id: "listen-speak-real", file: "../券商IT英语词汇表_听说句库_规则真实句.md", name: "听说句库·规则真实句（听写/跟读）" },
];

const samples = SOURCES.map((s) => {
  const text = fs.readFileSync(new URL(s.file, import.meta.url), "utf8");
  const cards = parseMarkdown(text, "").map((e) => ({
    front: e.front, back: e.back, example: e.example, category: e.category,
  }));
  return { id: s.id, name: s.name, count: cards.length, cards };
});

const banner = "// AUTO-GENERATED by gen_samples.mjs — do not edit by hand.\n";
const body = "window.VOCAB_SAMPLES = " + JSON.stringify(samples) + ";\n";
fs.writeFileSync(new URL("samples.js", import.meta.url), banner + body);

samples.forEach((s) => console.log(`${s.name}: ${s.count} 词`));
console.log("Wrote samples.js");
