// Mine high-frequency multi-word phrases (collocations) from the rule corpus and
// emit phrases.js -> window.RULE_PHRASES = { items:[{p,n,ex}] }.
// Usage: node gen_phrases.mjs
import fs from "node:fs";

const dir = new URL("./", import.meta.url);
const src = fs.readFileSync(new URL("corpus.js", dir), "utf8");
const data = JSON.parse(src.slice(src.indexOf("{"), src.lastIndexOf("}") + 1));
const items = data.items || [];

const MINCOUNT = 8;   // keep phrases seen at least this many times
const MAX = 800;      // final phrase count cap
const NMIN = 2, NMAX = 4;

const STOP = new Set(
  ("a an the this that these those of to in on at for with by from into onto upon over under above below " +
   "between among within without through during before after since until while and or but nor so yet as if " +
   "then than because although though unless whether it its is are was were be been being am do does did done " +
   "have has had having will would shall should may might must can could not no also such any all each every " +
   "some most more much many few less least own same other another both either neither per via there here " +
   "their they them we us our you your i me my he she his her him who whom whose which what when where why how " +
   "about against out off up down again further once only very too just").split(/\s+/)
);

// Split a paragraph into short clauses (period/semicolon/colon boundaries) for cleaner phrases + examples.
function splitSents(t) {
  return (String(t).match(/[^.!?;:]+[.!?;:]?/g) || [String(t)]).map((s) => s.trim()).filter((s) => s.length > 1);
}
const ok = (w) => w.length >= 3 && !STOP.has(w);

const counts = new Map();
for (const it of items) {
  for (const sent of splitSents(it.text)) {
    const toks = sent.toLowerCase().match(/[a-z][a-z'-]+/g) || [];
    for (let n = NMIN; n <= NMAX; n++) {
      for (let i = 0; i + n <= toks.length; i++) {
        const gram = toks.slice(i, i + n);
        // Content collocation: both ends are substantive words (not function words).
        if (!ok(gram[0]) || !ok(gram[n - 1])) continue;
        if (gram.some((w) => w.length < 2)) continue;
        const key = gram.join(" ");
        counts.set(key, (counts.get(key) || 0) + 1);
      }
    }
  }
}

// Rank: frequency, with a small boost for longer domain phrases.
let ranked = [];
for (const [p, n] of counts) {
  if (n < MINCOUNT) continue;
  const words = p.split(" ").length;
  ranked.push({ p, n, score: n * (words >= 3 ? 1.1 : 1) });
}
ranked.sort((a, b) => b.score - a.score);
ranked = ranked.slice(0, Math.round(MAX * 1.6));

// Drop shorter grams almost always contained in a longer, similarly-frequent gram.
const cnt = new Map(ranked.map((r) => [r.p, r.n]));
const longer = ranked.filter((r) => r.p.split(" ").length >= 3).map((r) => r.p);
const redundant = new Set();
for (const r of ranked) {
  if (r.p.split(" ").length !== 2) continue;
  const pad = " " + r.p + " ";
  for (const q of longer) {
    if ((" " + q + " ").includes(pad) && cnt.get(q) >= r.n * 0.8) { redundant.add(r.p); break; }
  }
}
const finalPhrases = ranked.filter((r) => !redundant.has(r.p)).slice(0, MAX);

// Attach a real example clause for each kept phrase (first-word index for speed).
const need = new Map();
const byFirst = new Map();
for (const r of finalPhrases) {
  need.set(r.p, r);
  const fw = r.p.split(" ")[0];
  if (!byFirst.has(fw)) byFirst.set(fw, []);
  byFirst.get(fw).push(r.p);
}
let remaining = finalPhrases.length;
outer: for (const it of items) {
  if (remaining <= 0) break;
  for (const sent of splitSents(it.text)) {
    const low = sent.toLowerCase();
    const toks = low.match(/[a-z][a-z'-]+/g) || [];
    const seen = new Set();
    for (const w of toks) {
      if (seen.has(w) || !byFirst.has(w)) continue;
      seen.add(w);
      for (const p of byFirst.get(w)) {
        const r = need.get(p);
        if (r && !r.ex && (" " + low + " ").includes(" " + p + " ")) {
          let ex = sent.replace(/\s+/g, " ").trim();
          if (ex.length > 200) ex = ex.slice(0, 200).replace(/\s+\S*$/, "") + "…";
          r.ex = ex;
          remaining--;
        }
      }
    }
    if (remaining <= 0) break outer;
  }
}

const out = finalPhrases
  .map((r) => ({ p: r.p, n: r.n, ex: r.ex || "" }))
  .sort((a, b) => b.n - a.n);
const banner = "// AUTO-GENERATED by gen_phrases.mjs: high-frequency phrases mined from 88 rule PDFs.\n";
fs.writeFileSync(new URL("phrases.js", dir), banner + "window.RULE_PHRASES = " + JSON.stringify({ items: out }) + ";\n");

console.log("unique grams:", counts.size, "-> kept:", out.length, "| with example:", out.filter((r) => r.ex).length);
console.log("TOP 25:");
out.slice(0, 25).forEach((r, i) => console.log(String(i + 1).padStart(2), r.n, r.p));
