// Grammar breakdown of the rule sentence library (authored for study).
window.RULE_GRAMMAR = {
  patterns: [
    { name: "shall / must / may / will — 义务与许可", tip: "法规英语的核心：shall、must = 强制义务（应/必须）；may = 许可（可）；will = 客观将发生。读到 shall 一律理解为「必须」。", eg: "The delivering member must notify the receiving member of their intention to deliver.", template: "[主语] shall / must / may [动词原形] …" },
    { name: "被动语态 be + 过去分词", tip: "规则强调「动作被执行」而非谁执行，故大量用被动。常与情态连用：shall be effected / will be settled / must be executed。", eg: "The settlement shall be effected in accordance with the Operational Procedures.", template: "[某事物] shall / will be [过去分词] (by …)" },
    { name: "条件从句 If / Where / Unless / Provided that", tip: "If = 如果；Where ≈ if（在…情形下）；Unless = 除非；Provided that = 前提是。从句常用一般现在时表将来。", eg: "If the Theoretical Price is not formed, the trading system will cancel any outstanding market order.", template: "If / Where [条件], [主句 shall / will 做…]" },
    { name: "定语从句 which / that / who", tip: "which / that 引导，修饰紧挨的名词，从句内有自己的谓语；主语与其谓语常被从句隔开，注意找回主干。", eg: "The Member which submits a new trade report shall ensure the report is amended.", template: "[名词] which / that [从句谓语] …" },
    { name: "使役 / 要求结构 require sb to do、enable sb to do、cause sth to be done", tip: "require sb to do = 要求某人做；enable sb to do = 使某人能做；cause sth to be done = 导致某事被…。be required / entitled to do = 被要求 / 有权做。", eg: "HKSCC may require the Long Participant to provide further information.", template: "[主语] may require / enable [宾语] to [do]" },
    { name: "后置修饰：介词短语 + 分词", tip: "法规靠「名词 + 后置修饰」叠加信息：in respect of（就…而言）、in accordance with（依照）、pursuant to（依据）、arising out of（由…产生的）、specified below（下列规定的）。", eg: "obligations to deliver Eligible Securities arising out of Market Contracts", template: "[名词] arising out of / in respect of / specified below …" },
    { name: "并列结构 v1, v2 or v3", tip: "用 and / or 并列多个动词或名词，共享同一主语或情态动词，读时先抓住被共享的主干。", eg: "Members may amend or cancel, suspend or activate any Orders.", template: "[主语] may [v1], [v2] or [v3] [宾语]" },
    { name: "无生命主语 + will / shall（系统 / 机构作主语）", tip: "规则常以「系统 / 交易所 / 公司」作主语 + will / shall，客观陈述规则动作，是最典型的规则句骨架。", eg: "The trading system will cancel any outstanding market order.", template: "[System / Exchange / Corporation] will / shall [do]" }
  ],
  items: [
    { sec: "一、交收 · 过户 · 交割",
      en: "The settlement of Transfer Instructions and Cross-Border Transfer Instructions shall be effected in accordance with the Operational Procedures.",
      cn: "过户指示与跨境过户指示的交收，应按照操作程序办理。",
      core: "The settlement … shall be effected（主语 + 情态 shall + 被动 be effected）",
      points: ["被动：shall be effected —— 情态 shall + be + 过去分词，「应被办理」", "长主语：The settlement of A and B —— of 短语作定语", "状语：in accordance with 依照…（高频）"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "In addition, the Corporation itself may determine that some or all transactions in a security shall settle on a trade-for-trade basis.",
      cn: "此外，本公司可自行决定某证券的部分或全部交易按逐笔（非净额）方式交收。",
      core: "the Corporation may determine that [宾语从句]",
      points: ["宾语从句：may determine that … —— 许可 may + that 从句", "强调：itself 反身代词作同位语，强调「自行」", "搭配：settle on a … basis 以…方式交收"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "The Foreign Security Accounting Operation produces Foreign Security receive and deliver instructions which identify the receive and deliver obligations of Members.",
      cn: "外国证券记账处理会生成外国证券的收付指示，用以明确会员的收付义务。",
      core: "The Operation produces instructions（主 + 谓 + 宾）",
      points: ["定语从句：which identify … 修饰 instructions", "并列：receive and deliver 作定语（收/付）", "时态：一般现在时表客观功能"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "HKSCC may effect partial deliveries in respect of its obligations to deliver Eligible Securities arising out of Market Contracts.",
      cn: "就市场合约产生的交付合资格证券义务，HKSCC 可进行部分交付。",
      core: "HKSCC may effect partial deliveries（主 + may + 谓 + 宾）",
      points: ["状语：in respect of 就…而言", "不定式作定语：obligations to deliver … 要交付…的义务", "分词作定语：arising out of Market Contracts 由市场合约产生的"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "A Buy-in pursuant to this Rule will be settled under the Isolated Trades System.",
      cn: "依据本规则进行的强制买入，将在独立交易系统下交收。",
      core: "A Buy-in will be settled（主 + 将来被动）",
      points: ["后置定语：pursuant to this Rule 依据本规则", "将来被动：will be settled", "状语：under … 在…系统下"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "The delivering member must notify the receiving member timeously of their intention to deliver.",
      cn: "交券会员必须及时将其交付意向通知收券会员。",
      core: "The member must notify sb of sth",
      points: ["搭配：notify sb of sth 通知某人某事", "义务：must 必须", "分词作定语：delivering / receiving 交券方 / 收券方"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "Only Brokers may mark a Split Transfer or a Renunciation and Split Transfer.",
      cn: "只有经纪商可以标记拆分过户，或放弃并拆分过户。",
      core: "Only Brokers may mark A or B",
      points: ["强调：Only 置句首强调「仅」", "许可：may", "并列宾语：A or B"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "A member must, by no later than 18h00, ensure that the CSDP of the member commits to settle the said transaction.",
      cn: "会员必须在不迟于 18:00 前，确保其中央证券存管参与者承诺交收该笔交易。",
      core: "A member must ensure that [从句]",
      points: ["宾语从句：ensure that …", "插入状语：by no later than 18h00 插在主谓之间", "法律用词：the said transaction 该（前述）交易"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "Member firms should cooperate with the Exchange to ensure timely settlement, including making every effort to settle outstanding unsettled short positions.",
      cn: "会员公司应与交易所配合以确保及时交收，包括尽力了结尚未交收的空头头寸。",
      core: "Member firms should cooperate … to ensure …",
      points: ["情态：should 应当（弱于 must）", "目的：to ensure 不定式表目的", "举例：including + V-ing 包括…"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "The DSS shall also cancel matched instructions that have not been settled after the lapse of sixty business days.",
      cn: "对已配对但经过六十个营业日仍未交收的指示，系统亦将予以取消。",
      core: "The DSS shall cancel instructions（主 + shall + 谓 + 宾）",
      points: ["定语从句：that have not been settled 修饰 instructions（现在完成被动）", "分词作定语：matched 已配对的", "状语：after the lapse of … 在…期满后"] },

    { sec: "二、订单 · 交易",
      en: "Members may amend or cancel, suspend or activate any Orders that have not been executed or that have been partially executed.",
      cn: "会员可对尚未成交或部分成交的订单进行修改、撤销、暂停或激活。",
      core: "Members may [v1…v4] any Orders",
      points: ["并列谓语：amend or cancel, suspend or activate 共享 may", "两定语从句并列：that have not been executed / that have been partially executed", "现在完成被动：have been executed"] },
    { sec: "二、订单 · 交易",
      en: "If the Theoretical Price is not formed, the trading system will cancel any outstanding market order.",
      cn: "若无法形成理论价格，交易系统将取消所有未成交的市价单。",
      core: "If [条件], the system will cancel …",
      points: ["条件从句：If …（一般现在时表将来）", "主句将来时：will cancel", "词义：outstanding 未成交的 / 未了结的"] },
    { sec: "二、订单 · 交易",
      en: "All-Or-None Orders are Orders that must be executed in full and cannot be partially executed.",
      cn: "全数成交（AON）订单必须全额成交，不能部分成交。",
      core: "AON Orders are Orders that [从句]",
      points: ["定语从句：that must … and cannot …（两谓语并列）", "情态被动：must be / cannot be executed", "状语：in full 全额"] },
    { sec: "二、订单 · 交易",
      en: "If these aspects of an Order require amendment, the Member shall cancel the Order and submit a new Order.",
      cn: "若订单的这些要素需要修改，会员应撤销该订单并提交新订单。",
      core: "If [条件], the Member shall cancel … and submit …",
      points: ["条件从句：If … require amendment", "并列谓语：shall cancel … and submit …", "及物动词：require + 名词"] },
    { sec: "二、订单 · 交易",
      en: "If the order is not fully executed, the non-executed part will be placed in the book as a market order.",
      cn: "若订单未全部成交，未成交部分将作为市价单挂入订单簿。",
      core: "If [条件], the part will be placed …",
      points: ["将来被动：will be placed", "as：作为…（表身份）", "构词：non-executed 前缀 non- 表否定"] },
    { sec: "二、订单 · 交易",
      en: "The Market may cancel any Order or Transaction that in its reasonable judgment does not comply with Applicable Law.",
      cn: "交易所可取消其合理判断认为不符合适用法律的任何订单或交易。",
      core: "The Market may cancel any Order or Transaction",
      points: ["定语从句：that … does not comply with 修饰 Order/Transaction", "插入语：in its reasonable judgment 作状语", "搭配：comply with 遵守 / 符合"] },
    { sec: "二、订单 · 交易",
      en: "The Member which submits a new trade report shall ensure that the previous erroneous trade report is cancelled and amended.",
      cn: "提交新成交报告的会员，应确保先前错误的成交报告已被取消并更正。",
      core: "The Member … shall ensure that [从句]",
      points: ["定语从句：which submits … 修饰 Member（主谓被隔开）", "宾语从句：ensure that …", "被动并列：is cancelled and amended"] },
    { sec: "二、订单 · 交易",
      en: "Members may also submit a request to cancel or amend a trade through the Nasdaq Fixed Income Trading System.",
      cn: "会员亦可通过 Nasdaq 固定收益交易系统提交撤销或修改某笔成交的请求。",
      core: "Members may submit a request",
      points: ["不定式作定语：to cancel or amend 修饰 request", "方式状语：through …", "许可：may also 也可"] },
    { sec: "二、订单 · 交易",
      en: "The same procedure will apply to the correction of a trade report during a system problem.",
      cn: "系统故障期间更正成交报告时，适用同样的流程。",
      core: "The procedure will apply to …",
      points: ["搭配：apply to 适用于", "时间状语：during … 在…期间", "of 短语作定语：the correction of …"] },
    { sec: "二、订单 · 交易",
      en: "A member firm should not submit a publishing trade report where one has already been submitted to the Exchange.",
      cn: "若已向交易所提交过发布性成交报告，会员公司不应再提交一份。",
      core: "A firm should not submit … where [条件从句]",
      points: ["禁止：should not 不应", "where ≈ if 在…情形下", "替代词：one = a report（避免重复）"] },
    { sec: "二、订单 · 交易",
      en: "Member firms must ensure that the settlement due date is included in the trade report where the trade is for non-standard settlement.",
      cn: "对于非标准交收的成交，会员公司必须确保成交报告中包含交收到期日。",
      core: "firms must ensure that [从句] where [条件]",
      points: ["宾语从句：ensure that …", "被动：is included 被包含", "条件从句：where … 在…情形下"] },
    { sec: "二、订单 · 交易",
      en: "The trading system will determine whether any further delay is applicable to the re-booked trade, otherwise it will publish immediately.",
      cn: "交易系统将判断重新入账的成交是否需要进一步延迟，否则立即公布。",
      core: "system will determine whether [从句], otherwise it will publish",
      points: ["whether 宾语从句：determine whether … 判断是否", "连接副词：otherwise 否则", "构词：re-booked 重新入账的"] },

    { sec: "三、通知 · 申请 · 受理",
      en: "Participants shall maintain sufficient funds in their Designated Bank Accounts to enable HKSCC to effect such subscription instructions.",
      cn: "参与者应在其指定银行账户中保持充足资金，以便 HKSCC 执行该等认购指示。",
      core: "Participants shall maintain funds to enable HKSCC to …",
      points: ["义务：shall maintain 应保持", "使役 + 目的：to enable sb to do 以使某人能做", "法律指代：such 该等"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "An Investor Participant may provide such details to HKSCC at the Customer Service Centre.",
      cn: "投资者参与者可在客户服务中心向 HKSCC 提供该等资料。",
      core: "Participant may provide details to HKSCC",
      points: ["搭配：provide sth to sb 向某人提供某物", "许可：may", "地点状语：at …"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "HKSCC may require the Long Participant to provide further information to substantiate its complaint.",
      cn: "HKSCC 可要求好仓参与者提供进一步资料以证实其投诉。",
      core: "HKSCC may require sb to do",
      points: ["使役：require sb to do 要求某人做", "目的：to substantiate … 以证实", "词义：further 进一步的"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "In such case, JSCC shall notify Clearing Participants to that effect in advance.",
      cn: "在此情形下，JSCC 应事先就此通知清算参与者。",
      core: "JSCC shall notify sb",
      points: ["短语：to that effect 就此（作此意思的通知）", "状语：in advance 事先", "句首状语：In such case"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "The Authority may at its discretion accept or reject the request for cancellation.",
      cn: "当局可自行酌情接受或拒绝该撤销请求。",
      core: "The Authority may accept or reject the request",
      points: ["插入状语：at its discretion 酌情", "并列谓语：accept or reject", "of/for 定语：the request for …"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "Where it does not accept the resignation, it shall provide a reasoned answer.",
      cn: "如不接受该辞任，应给出附理由的答复。",
      core: "Where [条件], it shall provide …",
      points: ["条件从句：Where … 在…情况下", "义务：shall provide 应提供", "分词作形容词：reasoned 有理由的"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "If ATHEXCSD declines to accept the application, it shall provide a reasoned reply to the candidate.",
      cn: "若受理机构拒绝该申请，应向申请人给出附理由的答复。",
      core: "If [条件], it shall provide a reply to sb",
      points: ["搭配：decline to do 拒绝做", "结构：provide … to sb 向某人提供", "词组：reasoned reply 附理由的答复"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "If the conditions are met, ATHEXCSD shall accept the resignation and notify the resigning Participant accordingly.",
      cn: "若满足相关条件，机构应接受该辞任并相应通知辞任参与者。",
      core: "If [条件], it shall accept … and notify …",
      points: ["被动：conditions are met 条件被满足", "并列谓语：accept … and notify …", "连接副词：accordingly 相应地"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "The resignation shall apply provided that the Member has settled any pending matters within the above time-limit.",
      cn: "该辞任的生效，以会员在上述时限内已了结任何未决事项为前提。",
      core: "The resignation shall apply provided that [条件]",
      points: ["条件连词：provided that 前提是", "现在完成：has settled 已了结", "词义：pending 待决的 / 未决的"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "OCC shall notify the Corporation of all Participating Members that have executed such agreements.",
      cn: "OCC 应将所有已签署该等协议的参与会员通知本公司。",
      core: "OCC shall notify sb of sth",
      points: ["搭配：notify sb of sth 通知某人某事", "定语从句：that have executed … 修饰 Members", "词义：execute 签署（执行）协议"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "As part of its membership application, each applicant shall obtain and provide to the Corporation an LEI.",
      cn: "作为会员申请的一部分，每位申请人应取得并向本公司提供法人机构识别编码（LEI）。",
      core: "each applicant shall obtain and provide … an LEI",
      points: ["句首状语：As part of … 作为…的一部分", "并列谓语：obtain and provide", "宾语后置：provide to sb + 较长宾语 an LEI"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "Euronext Clearing shall receive evidence of the approval prior to validating the transfer.",
      cn: "Euronext Clearing 应在确认该转移之前收到批准的证明。",
      core: "EC shall receive evidence",
      points: ["prior to + 名词 / V-ing：在…之前（= before）", "动名词：validating 作 prior to 的宾语", "of 定语：evidence of …"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "Euronext Clearing shall indicate the moment from which the Member's new arrangement shall have effect.",
      cn: "Euronext Clearing 应指明会员新安排自何时起生效。",
      core: "EC shall indicate the moment",
      points: ["介词 + 关系代词：from which … 引导定语从句修饰 moment", "搭配：have effect 生效", "所有格：the Member's 作定语"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "The Corporation will reject a transfer if the details contain an edit or format error.",
      cn: "若明细存在校验或格式错误，本公司将拒绝该转移。",
      core: "The Corporation will reject a transfer if [条件]",
      points: ["主句将来 + if 后置条件从句", "词义：contain 含有", "并列定语：an edit or format error"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "Failure to timely submit a confirmation will cause the transfer request to be deleted.",
      cn: "未能及时提交确认，将导致该转移请求被删除。",
      core: "Failure … will cause sth to be done",
      points: ["名词化主语：Failure to do 未能做", "使役：cause sth to do 导致某物…", "不定式被动：to be deleted 被删除"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "Once a Receiving Member has accelerated the transfer, the transfer will be in accelerated status.",
      cn: "一旦收方会员加速了该转移，该转移即处于加速状态。",
      core: "Once [条件], the transfer will be …",
      points: ["从句：Once … 一旦…", "现在完成：has accelerated 已加速", "搭配：in … status 处于…状态"] },

    { sec: "四、清算 · 保证金 · 担保品",
      en: "The Clearing Member will continue to be required to provide Collateral and settle Open Positions as they fall due.",
      cn: "清算会员仍须提供担保品，并在未平仓头寸到期时予以交收。",
      core: "The Member will continue to be required to provide … and settle …",
      points: ["搭配：continue to do 继续做", "被动义务：be required to do 被要求做（= must）", "时间从句：as they fall due 当其到期时"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "ASX Clear will require Clearing Participants to provide additional Cover in the form, manner and amount specified below.",
      cn: "ASX Clear 将要求清算参与者按下列规定的形式、方式与金额提供追加担保。",
      core: "ASX Clear will require sb to provide …",
      points: ["使役：require sb to do", "三名词并列作状语：in the form, manner and amount", "分词作定语：specified below 下列规定的"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "The delivery obligation of Eurex Clearing AG vis-à-vis the Clearing Member entitled to the delivery shall expire with debt discharging effect.",
      cn: "Eurex Clearing AG 对有权受领交付的清算会员的交付义务，将以清偿之效力而消灭。",
      core: "The delivery obligation … shall expire",
      points: ["超长主语：obligation of X vis-à-vis Y", "分词作定语：entitled to … 有权…的（修饰 Member）", "状语：with … effect 以…效力"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "Eurex Clearing AG shall specify in the notification a reasonable period of time during which such suspension or limitation shall apply.",
      cn: "Eurex Clearing AG 应在通知中指明该等暂停或限制适用的合理期间。",
      core: "EC shall specify a period（宾语后置）",
      points: ["状语插入动宾之间：specify in the notification + 长宾语", "介词 + 关系代词：during which … 定语从句修饰 period", "指代：such 该等"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "The Clearing Member shall prove to BME CLEARING that it holds such participant status, in the way that BME CLEARING shall determine.",
      cn: "清算会员应按 BME CLEARING 确定的方式，向其证明其具有该等参与者资格。",
      core: "The Member shall prove to sb that [从句]",
      points: ["结构：prove to sb that … 向某人证明", "定语从句：in the way that … 以…的方式", "指代：such participant status 该等资格"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "BME CLEARING will be entitled to take the decision to accept or refuse any Voluntary Contribution.",
      cn: "BME CLEARING 有权决定接受或拒绝任何自愿出资。",
      core: "BME CLEARING will be entitled to take the decision",
      points: ["搭配：be entitled to do 有权做", "不定式作定语：the decision to do", "并列：accept or refuse"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "ASX Clear will cancel the registration of Derivatives CCP Contracts which a Participant has advised are to be closed out.",
      cn: "对于参与者已告知将予平仓的衍生品 CCP 合约，ASX Clear 将注销其登记。",
      core: "ASX Clear will cancel the registration of Contracts",
      points: ["定语从句：which … are to be closed out 修饰 Contracts", "从句内插入：a Participant has advised 参与者已告知", "be to be done：将被…（be to 表规定 + 被动）"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "ASX Clear will notify Participants of a rejection of a Tender Notice via the DCS Messages facility.",
      cn: "ASX Clear 将通过 DCS 消息功能，将交割通知被拒一事通知参与者。",
      core: "ASX Clear will notify sb of sth",
      points: ["搭配：notify sb of sth", "of 短语：a rejection of …（…被拒）", "方式：via … 通过…"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "ASX Clear will generally notify each Participant by sending a Clearing Message at least once each Business Day.",
      cn: "ASX Clear 通常会在每个营业日至少一次，通过发送清算消息通知每位参与者。",
      core: "ASX Clear will notify each Participant",
      points: ["方式：by + V-ing 通过做…", "频率：generally 通常、at least once each Business Day", "动名词：sending 作 by 的宾语"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "ASX Clear will only accept Tender Documentation if it is submitted on a Business Day within the current Delivery Period.",
      cn: "仅当交割文件在当前交割期内的营业日提交时，ASX Clear 才会受理。",
      core: "ASX Clear will only accept … if [条件]",
      points: ["only … if …：仅当…才", "被动：is submitted 被提交", "范围状语：within … 在…期内"] },

    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "Each Market Participant, Adviser and Dealer must ensure their conduct promotes and helps maintain an orderly market.",
      cn: "每位市场参与者、顾问及交易商都必须确保其行为有助于促进并维持有序市场。",
      core: "Each … must ensure [that] their conduct promotes and helps …",
      points: ["宾语从句：ensure (that) …（省略 that）", "并列谓语：promotes and helps maintain", "搭配：help (to) do 有助于做"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "Testing shall be conducted in the manner prescribed by and shall comply with the instructions issued by Nasdaq Baltic.",
      cn: "测试应按 Nasdaq Baltic 规定的方式进行，并遵守其发布的指示。",
      core: "Testing shall be conducted … and shall comply with …",
      points: ["被动：shall be conducted 应被进行", "分词作定语：prescribed by / issued by 由…规定 / 发布的", "两 shall 并列"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "The Trading Member's emergency contact persons must be contactable at all times, and must immediately notify SGX-ST in the event of emergencies.",
      cn: "交易会员的紧急联系人必须始终可联系到，并在发生紧急情况时立即通知 SGX-ST。",
      core: "contact persons must be contactable … and must notify …",
      points: ["be + 形容词：must be contactable 必须可联系", "条件状语：in the event of … 一旦发生…", "两 must 并列谓语"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "Full trading participants, trading participants and foreign participants must ensure that investors under their responsibility comply with all provisions of this article.",
      cn: "完全交易参与者、交易参与者及外国参与者，必须确保其负责的投资者遵守本条全部规定。",
      core: "[三类主语] must ensure that [从句]",
      points: ["三个并列主语共享 must ensure", "后置定语：under their responsibility 其负责的", "搭配：comply with 遵守"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "The risk criteria which will be used and limits which will be applied shall be determined by the Board of Directors.",
      cn: "所采用的风险标准与所适用的限额，应由董事会确定。",
      core: "The criteria … and limits … shall be determined by …",
      points: ["两定语从句：which will be used / which will be applied", "被动 + 施动者：shall be determined by …", "并列主语：criteria and limits"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "Such information must be complete, must not be corrupted and must be legible at the time of receipt by LCH SA.",
      cn: "该等信息在 LCH SA 收到时必须完整、未损坏且清晰可读。",
      core: "information must be complete, must not be corrupted and must be legible",
      points: ["三个 must 并列（be complete / not be corrupted / be legible）", "时间状语：at the time of receipt 在收到时", "施动者：by LCH SA 被…收到"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "Systems should be designed to ensure a high degree of security and operational reliability and should have adequate, scalable capacity.",
      cn: "系统的设计应确保高度的安全性与运行可靠性，并具备充足、可扩展的容量。",
      core: "Systems should be designed … and should have …",
      points: ["被动 + 目的：should be designed to do 应被设计以…", "两 should 并列", "并列形容词：adequate, scalable"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "A CSD should maintain securities in an immobilised or dematerialised form for their transfer by book entry.",
      cn: "中央证券存管机构应以固定化或无纸化形式保管证券，以便通过簿记方式转让。",
      core: "A CSD should maintain securities",
      points: ["方式状语：in a … form 以…形式", "for + 名词表目的：for their transfer 以便转让", "方式：by book entry 通过簿记"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "The FMI should provide clear descriptions of priced services for comparability purposes.",
      cn: "金融市场基础设施应对收费服务提供清晰说明，以便进行比较。",
      core: "The FMI should provide descriptions",
      points: ["情态：should provide 应提供", "of 定语：descriptions of priced services", "目的状语：for … purposes 为…目的"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "SIX x-clear will initiate the necessary measures, and further steps will be defined within the Emergency and Crisis Organization.",
      cn: "SIX x-clear 将启动必要措施，后续步骤将在应急与危机组织框架内确定。",
      core: "SIX will initiate measures, and steps will be defined",
      points: ["and 连接两独立分句（主动 + 被动）", "将来被动：will be defined 将被确定", "范围：within … 在…内"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "The Market may impose such fees and other charges as it may from time to time determine and publish by Circular.",
      cn: "交易所可征收其不时确定并以通函公布的费用及其他收费。",
      core: "The Market may impose such fees and charges as [从句]",
      points: ["such … as …：像…那样的（as 引导定语从句）", "高频状语：from time to time 不时", "并列谓语：determine and publish"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "The Market shall determine and may modify the Trading Hours and Business Days for trading Regulated Derivatives, by disclosure in a Circular.",
      cn: "交易所应以通函披露的方式，确定并可修改受监管衍生品的交易时间与营业日。",
      core: "The Market shall determine and may modify …",
      points: ["不同情态并列：shall determine（应确定）/ may modify（可修改）", "用途：for trading … 为…", "方式：by disclosure in a Circular 以通函披露"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "SGX-ST will determine the remuneration of the Manager, which must be paid by the Trading Member.",
      cn: "SGX-ST 将确定管理人的报酬，该报酬须由交易会员支付。",
      core: "SGX-ST will determine the remuneration, which must be paid …",
      points: ["非限制性定语从句：, which … 补充说明 remuneration", "义务 + 被动 + 施动者：must be paid by …", "of 定语：the remuneration of …"] }
  ],
  // 每句"最突出的句式"索引（对应 patterns），-1 表示无单一突出结构、不纳入句型识别题
  patternOf: [
    1, -1, 3, 5, 1, -1, 6, -1, -1, 3,
    6, 2, 3, 2, 2, 3, 3, 6, -1, 2,
    2, -1, 4, -1, 4, -1, 6, 2, 2, 2,
    2, 3, 6, -1, 3, 2, 4, 2, 4, 4,
    5, 3, 3, 6, 3, -1, -1, 2, 6, 1,
    6, -1, 3, 6, 6, 5, -1, 6, 3, 6,
    3
  ]
};
