// Grammar breakdown of the rule sentence library (authored for study).
window.RULE_GRAMMAR = {
  patterns: [
    { name: "shall / must / may / will — 义务与许可", tip: "法规英语的核心：shall、must = 强制义务（应/必须）；may = 许可（可）；will = 客观将发生。读到 shall 一律理解为「必须」。", eg: "The delivering member must notify the receiving member of their intention to deliver.", template: "[主语] shall / must / may [动词原形] …" },
    { name: "被动语态 be + 过去分词", tip: "规则强调「动作被执行」而非谁执行，故大量用被动。常与情态连用：shall be effected / will be settled / must be executed。", eg: "The settlement shall be effected in accordance with the Operational Procedures.", template: "[某事物] shall / will be [过去分词] (by …)" },
    { name: "条件从句 If / Where / Unless / Provided that", tip: "If = 如果；Where ≈ if（在…情形下）；Unless = 除非；Provided that = 前提是。从句常用一般现在时表将来。", eg: "If the Theoretical Price is not formed, the trading system will cancel any outstanding market order.", template: "If / Where [条件], [主句 shall / will 做…]" },
    { name: "定语从句 which / that / who", tip: "which / that 引导，修饰紧挨的名词，从句内有自己的谓语；主语与其谓语常被从句隔开，注意找回主干。", eg: "The Member which submits a new trade report shall ensure the report is amended.", template: "[名词] which / that [从句谓语] …" },
    { name: "使役 / 要求结构 require sb to do、enable sb to do、cause sth to be done", tip: "require sb to do = 要求某人做；enable sb to do = 使某人能做；cause sth to be done = 导致某事被…。be required / entitled to do = 被要求 / 有权做。", eg: "HKSCC may require the Long Participant to provide further information.", template: "[主语] may require / enable [宾语] to [do]" },
    { name: "后置修饰：介词短语 + 分词", tip: "法规靠「名词 + 后置修饰」叠加信息：in respect of（就…而言）、in accordance with（依照）、pursuant to（依据）、arising out of（由…产生的）、specified below（下列规定的）。", eg: "obligations to deliver Eligible Securities arising out of Market Contracts", template: "[名词] arising out of / in respect of / specified below …" },
    { name: "并列结构 v1, v2 or v3", tip: "用 and / or 并列多个动词或名词，共享同一主语或情态动词，读时先抓住被共享的主干。", eg: "Members may amend or cancel, suspend or activate any Orders.", template: "[主语] may [v1], [v2] or [v3] [宾语]" },
    { name: "无生命主语 + will / shall（系统 / 机构作主语）", tip: "规则常以「系统 / 交易所 / 公司」作主语 + will / shall，客观陈述规则动作，是最典型的规则句骨架。", eg: "The trading system will cancel any outstanding market order.", template: "[System / Exchange / Corporation] will / shall [do]" }
  ],
  items: [
    { sec: "一、交收 · 过户 · 交割",
      en: "The settlement of Transfer Instructions and Cross-Border Transfer Instructions shall be effected in accordance with the Operational Procedures.",
      cn: "过户指示与跨境过户指示的交收，应按照操作程序办理。",
      core: "The settlement … shall be effected（主语 + 情态 shall + 被动 be effected）",
      points: ["被动：shall be effected —— 情态 shall + be + 过去分词，「应被办理」", "长主语：The settlement of A and B —— of 短语作定语", "状语：in accordance with 依照…（高频）"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "In addition, the Corporation itself may determine that some or all transactions in a security shall settle on a trade-for-trade basis.",
      cn: "此外，本公司可自行决定某证券的部分或全部交易按逐笔（非净额）方式交收。",
      core: "the Corporation may determine that [宾语从句]",
      points: ["宾语从句：may determine that … —— 许可 may + that 从句", "强调：itself 反身代词作同位语，强调「自行」", "搭配：settle on a … basis 以…方式交收"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "The Foreign Security Accounting Operation produces Foreign Security receive and deliver instructions which identify the receive and deliver obligations of Members.",
      cn: "外国证券记账处理会生成外国证券的收付指示，用以明确会员的收付义务。",
      core: "The Operation produces instructions（主 + 谓 + 宾）",
      points: ["定语从句：which identify … 修饰 instructions", "并列：receive and deliver 作定语（收/付）", "时态：一般现在时表客观功能"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "HKSCC may effect partial deliveries in respect of its obligations to deliver Eligible Securities arising out of Market Contracts.",
      cn: "就市场合约产生的交付合资格证券义务，HKSCC 可进行部分交付。",
      core: "HKSCC may effect partial deliveries（主 + may + 谓 + 宾）",
      points: ["状语：in respect of 就…而言", "不定式作定语：obligations to deliver … 要交付…的义务", "分词作定语：arising out of Market Contracts 由市场合约产生的"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "A Buy-in pursuant to this Rule will be settled under the Isolated Trades System.",
      cn: "依据本规则进行的强制买入，将在独立交易系统下交收。",
      core: "A Buy-in will be settled（主 + 将来被动）",
      points: ["后置定语：pursuant to this Rule 依据本规则", "将来被动：will be settled", "状语：under … 在…系统下"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "The delivering member must notify the receiving member timeously of their intention to deliver.",
      cn: "交券会员必须及时将其交付意向通知收券会员。",
      core: "The member must notify sb of sth",
      points: ["搭配：notify sb of sth 通知某人某事", "义务：must 必须", "分词作定语：delivering / receiving 交券方 / 收券方"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "Only Brokers may mark a Split Transfer or a Renunciation and Split Transfer.",
      cn: "只有经纪商可以标记拆分过户，或放弃并拆分过户。",
      core: "Only Brokers may mark A or B",
      points: ["强调：Only 置句首强调「仅」", "许可：may", "并列宾语：A or B"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "A member must, by no later than 18h00, ensure that the CSDP of the member commits to settle the said transaction.",
      cn: "会员必须在不迟于 18:00 前，确保其中央证券存管参与者承诺交收该笔交易。",
      core: "A member must ensure that [从句]",
      points: ["宾语从句：ensure that …", "插入状语：by no later than 18h00 插在主谓之间", "法律用词：the said transaction 该（前述）交易"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "Member firms should cooperate with the Exchange to ensure timely settlement, including making every effort to settle outstanding unsettled short positions.",
      cn: "会员公司应与交易所配合以确保及时交收，包括尽力了结尚未交收的空头头寸。",
      core: "Member firms should cooperate … to ensure …",
      points: ["情态：should 应当（弱于 must）", "目的：to ensure 不定式表目的", "举例：including + V-ing 包括…"] },
    { sec: "一、交收 · 过户 · 交割",
      en: "The DSS shall also cancel matched instructions that have not been settled after the lapse of sixty business days.",
      cn: "对已配对但经过六十个营业日仍未交收的指示，系统亦将予以取消。",
      core: "The DSS shall cancel instructions（主 + shall + 谓 + 宾）",
      points: ["定语从句：that have not been settled 修饰 instructions（现在完成被动）", "分词作定语：matched 已配对的", "状语：after the lapse of … 在…期满后"] },

    { sec: "二、订单 · 交易",
      en: "Members may amend or cancel, suspend or activate any Orders that have not been executed or that have been partially executed.",
      cn: "会员可对尚未成交或部分成交的订单进行修改、撤销、暂停或激活。",
      core: "Members may [v1…v4] any Orders",
      points: ["并列谓语：amend or cancel, suspend or activate 共享 may", "两定语从句并列：that have not been executed / that have been partially executed", "现在完成被动：have been executed"] },
    { sec: "二、订单 · 交易",
      en: "If the Theoretical Price is not formed, the trading system will cancel any outstanding market order.",
      cn: "若无法形成理论价格，交易系统将取消所有未成交的市价单。",
      core: "If [条件], the system will cancel …",
      points: ["条件从句：If …（一般现在时表将来）", "主句将来时：will cancel", "词义：outstanding 未成交的 / 未了结的"] },
    { sec: "二、订单 · 交易",
      en: "All-Or-None Orders are Orders that must be executed in full and cannot be partially executed.",
      cn: "全数成交（AON）订单必须全额成交，不能部分成交。",
      core: "AON Orders are Orders that [从句]",
      points: ["定语从句：that must … and cannot …（两谓语并列）", "情态被动：must be / cannot be executed", "状语：in full 全额"] },
    { sec: "二、订单 · 交易",
      en: "If these aspects of an Order require amendment, the Member shall cancel the Order and submit a new Order.",
      cn: "若订单的这些要素需要修改，会员应撤销该订单并提交新订单。",
      core: "If [条件], the Member shall cancel … and submit …",
      points: ["条件从句：If … require amendment", "并列谓语：shall cancel … and submit …", "及物动词：require + 名词"] },
    { sec: "二、订单 · 交易",
      en: "If the order is not fully executed, the non-executed part will be placed in the book as a market order.",
      cn: "若订单未全部成交，未成交部分将作为市价单挂入订单簿。",
      core: "If [条件], the part will be placed …",
      points: ["将来被动：will be placed", "as：作为…（表身份）", "构词：non-executed 前缀 non- 表否定"] },
    { sec: "二、订单 · 交易",
      en: "The Market may cancel any Order or Transaction that in its reasonable judgment does not comply with Applicable Law.",
      cn: "交易所可取消其合理判断认为不符合适用法律的任何订单或交易。",
      core: "The Market may cancel any Order or Transaction",
      points: ["定语从句：that … does not comply with 修饰 Order/Transaction", "插入语：in its reasonable judgment 作状语", "搭配：comply with 遵守 / 符合"] },
    { sec: "二、订单 · 交易",
      en: "The Member which submits a new trade report shall ensure that the previous erroneous trade report is cancelled and amended.",
      cn: "提交新成交报告的会员，应确保先前错误的成交报告已被取消并更正。",
      core: "The Member … shall ensure that [从句]",
      points: ["定语从句：which submits … 修饰 Member（主谓被隔开）", "宾语从句：ensure that …", "被动并列：is cancelled and amended"] },
    { sec: "二、订单 · 交易",
      en: "Members may also submit a request to cancel or amend a trade through the Nasdaq Fixed Income Trading System.",
      cn: "会员亦可通过 Nasdaq 固定收益交易系统提交撤销或修改某笔成交的请求。",
      core: "Members may submit a request",
      points: ["不定式作定语：to cancel or amend 修饰 request", "方式状语：through …", "许可：may also 也可"] },
    { sec: "二、订单 · 交易",
      en: "The same procedure will apply to the correction of a trade report during a system problem.",
      cn: "系统故障期间更正成交报告时，适用同样的流程。",
      core: "The procedure will apply to …",
      points: ["搭配：apply to 适用于", "时间状语：during … 在…期间", "of 短语作定语：the correction of …"] },
    { sec: "二、订单 · 交易",
      en: "A member firm should not submit a publishing trade report where one has already been submitted to the Exchange.",
      cn: "若已向交易所提交过发布性成交报告，会员公司不应再提交一份。",
      core: "A firm should not submit … where [条件从句]",
      points: ["禁止：should not 不应", "where ≈ if 在…情形下", "替代词：one = a report（避免重复）"] },
    { sec: "二、订单 · 交易",
      en: "Member firms must ensure that the settlement due date is included in the trade report where the trade is for non-standard settlement.",
      cn: "对于非标准交收的成交，会员公司必须确保成交报告中包含交收到期日。",
      core: "firms must ensure that [从句] where [条件]",
      points: ["宾语从句：ensure that …", "被动：is included 被包含", "条件从句：where … 在…情形下"] },
    { sec: "二、订单 · 交易",
      en: "The trading system will determine whether any further delay is applicable to the re-booked trade, otherwise it will publish immediately.",
      cn: "交易系统将判断重新入账的成交是否需要进一步延迟，否则立即公布。",
      core: "system will determine whether [从句], otherwise it will publish",
      points: ["whether 宾语从句：determine whether … 判断是否", "连接副词：otherwise 否则", "构词：re-booked 重新入账的"] },

    { sec: "三、通知 · 申请 · 受理",
      en: "Participants shall maintain sufficient funds in their Designated Bank Accounts to enable HKSCC to effect such subscription instructions.",
      cn: "参与者应在其指定银行账户中保持充足资金，以便 HKSCC 执行该等认购指示。",
      core: "Participants shall maintain funds to enable HKSCC to …",
      points: ["义务：shall maintain 应保持", "使役 + 目的：to enable sb to do 以使某人能做", "法律指代：such 该等"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "An Investor Participant may provide such details to HKSCC at the Customer Service Centre.",
      cn: "投资者参与者可在客户服务中心向 HKSCC 提供该等资料。",
      core: "Participant may provide details to HKSCC",
      points: ["搭配：provide sth to sb 向某人提供某物", "许可：may", "地点状语：at …"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "HKSCC may require the Long Participant to provide further information to substantiate its complaint.",
      cn: "HKSCC 可要求好仓参与者提供进一步资料以证实其投诉。",
      core: "HKSCC may require sb to do",
      points: ["使役：require sb to do 要求某人做", "目的：to substantiate … 以证实", "词义：further 进一步的"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "In such case, JSCC shall notify Clearing Participants to that effect in advance.",
      cn: "在此情形下，JSCC 应事先就此通知清算参与者。",
      core: "JSCC shall notify sb",
      points: ["短语：to that effect 就此（作此意思的通知）", "状语：in advance 事先", "句首状语：In such case"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "The Authority may at its discretion accept or reject the request for cancellation.",
      cn: "当局可自行酌情接受或拒绝该撤销请求。",
      core: "The Authority may accept or reject the request",
      points: ["插入状语：at its discretion 酌情", "并列谓语：accept or reject", "of/for 定语：the request for …"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "Where it does not accept the resignation, it shall provide a reasoned answer.",
      cn: "如不接受该辞任，应给出附理由的答复。",
      core: "Where [条件], it shall provide …",
      points: ["条件从句：Where … 在…情况下", "义务：shall provide 应提供", "分词作形容词：reasoned 有理由的"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "If ATHEXCSD declines to accept the application, it shall provide a reasoned reply to the candidate.",
      cn: "若受理机构拒绝该申请，应向申请人给出附理由的答复。",
      core: "If [条件], it shall provide a reply to sb",
      points: ["搭配：decline to do 拒绝做", "结构：provide … to sb 向某人提供", "词组：reasoned reply 附理由的答复"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "If the conditions are met, ATHEXCSD shall accept the resignation and notify the resigning Participant accordingly.",
      cn: "若满足相关条件，机构应接受该辞任并相应通知辞任参与者。",
      core: "If [条件], it shall accept … and notify …",
      points: ["被动：conditions are met 条件被满足", "并列谓语：accept … and notify …", "连接副词：accordingly 相应地"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "The resignation shall apply provided that the Member has settled any pending matters within the above time-limit.",
      cn: "该辞任的生效，以会员在上述时限内已了结任何未决事项为前提。",
      core: "The resignation shall apply provided that [条件]",
      points: ["条件连词：provided that 前提是", "现在完成：has settled 已了结", "词义：pending 待决的 / 未决的"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "OCC shall notify the Corporation of all Participating Members that have executed such agreements.",
      cn: "OCC 应将所有已签署该等协议的参与会员通知本公司。",
      core: "OCC shall notify sb of sth",
      points: ["搭配：notify sb of sth 通知某人某事", "定语从句：that have executed … 修饰 Members", "词义：execute 签署（执行）协议"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "As part of its membership application, each applicant shall obtain and provide to the Corporation an LEI.",
      cn: "作为会员申请的一部分，每位申请人应取得并向本公司提供法人机构识别编码（LEI）。",
      core: "each applicant shall obtain and provide … an LEI",
      points: ["句首状语：As part of … 作为…的一部分", "并列谓语：obtain and provide", "宾语后置：provide to sb + 较长宾语 an LEI"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "Euronext Clearing shall receive evidence of the approval prior to validating the transfer.",
      cn: "Euronext Clearing 应在确认该转移之前收到批准的证明。",
      core: "EC shall receive evidence",
      points: ["prior to + 名词 / V-ing：在…之前（= before）", "动名词：validating 作 prior to 的宾语", "of 定语：evidence of …"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "Euronext Clearing shall indicate the moment from which the Member's new arrangement shall have effect.",
      cn: "Euronext Clearing 应指明会员新安排自何时起生效。",
      core: "EC shall indicate the moment",
      points: ["介词 + 关系代词：from which … 引导定语从句修饰 moment", "搭配：have effect 生效", "所有格：the Member's 作定语"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "The Corporation will reject a transfer if the details contain an edit or format error.",
      cn: "若明细存在校验或格式错误，本公司将拒绝该转移。",
      core: "The Corporation will reject a transfer if [条件]",
      points: ["主句将来 + if 后置条件从句", "词义：contain 含有", "并列定语：an edit or format error"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "Failure to timely submit a confirmation will cause the transfer request to be deleted.",
      cn: "未能及时提交确认，将导致该转移请求被删除。",
      core: "Failure … will cause sth to be done",
      points: ["名词化主语：Failure to do 未能做", "使役：cause sth to do 导致某物…", "不定式被动：to be deleted 被删除"] },
    { sec: "三、通知 · 申请 · 受理",
      en: "Once a Receiving Member has accelerated the transfer, the transfer will be in accelerated status.",
      cn: "一旦收方会员加速了该转移，该转移即处于加速状态。",
      core: "Once [条件], the transfer will be …",
      points: ["从句：Once … 一旦…", "现在完成：has accelerated 已加速", "搭配：in … status 处于…状态"] },

    { sec: "四、清算 · 保证金 · 担保品",
      en: "The Clearing Member will continue to be required to provide Collateral and settle Open Positions as they fall due.",
      cn: "清算会员仍须提供担保品，并在未平仓头寸到期时予以交收。",
      core: "The Member will continue to be required to provide … and settle …",
      points: ["搭配：continue to do 继续做", "被动义务：be required to do 被要求做（= must）", "时间从句：as they fall due 当其到期时"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "ASX Clear will require Clearing Participants to provide additional Cover in the form, manner and amount specified below.",
      cn: "ASX Clear 将要求清算参与者按下列规定的形式、方式与金额提供追加担保。",
      core: "ASX Clear will require sb to provide …",
      points: ["使役：require sb to do", "三名词并列作状语：in the form, manner and amount", "分词作定语：specified below 下列规定的"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "The delivery obligation of Eurex Clearing AG vis-à-vis the Clearing Member entitled to the delivery shall expire with debt discharging effect.",
      cn: "Eurex Clearing AG 对有权受领交付的清算会员的交付义务，将以清偿之效力而消灭。",
      core: "The delivery obligation … shall expire",
      points: ["超长主语：obligation of X vis-à-vis Y", "分词作定语：entitled to … 有权…的（修饰 Member）", "状语：with … effect 以…效力"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "Eurex Clearing AG shall specify in the notification a reasonable period of time during which such suspension or limitation shall apply.",
      cn: "Eurex Clearing AG 应在通知中指明该等暂停或限制适用的合理期间。",
      core: "EC shall specify a period（宾语后置）",
      points: ["状语插入动宾之间：specify in the notification + 长宾语", "介词 + 关系代词：during which … 定语从句修饰 period", "指代：such 该等"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "The Clearing Member shall prove to BME CLEARING that it holds such participant status, in the way that BME CLEARING shall determine.",
      cn: "清算会员应按 BME CLEARING 确定的方式，向其证明其具有该等参与者资格。",
      core: "The Member shall prove to sb that [从句]",
      points: ["结构：prove to sb that … 向某人证明", "定语从句：in the way that … 以…的方式", "指代：such participant status 该等资格"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "BME CLEARING will be entitled to take the decision to accept or refuse any Voluntary Contribution.",
      cn: "BME CLEARING 有权决定接受或拒绝任何自愿出资。",
      core: "BME CLEARING will be entitled to take the decision",
      points: ["搭配：be entitled to do 有权做", "不定式作定语：the decision to do", "并列：accept or refuse"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "ASX Clear will cancel the registration of Derivatives CCP Contracts which a Participant has advised are to be closed out.",
      cn: "对于参与者已告知将予平仓的衍生品 CCP 合约，ASX Clear 将注销其登记。",
      core: "ASX Clear will cancel the registration of Contracts",
      points: ["定语从句：which … are to be closed out 修饰 Contracts", "从句内插入：a Participant has advised 参与者已告知", "be to be done：将被…（be to 表规定 + 被动）"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "ASX Clear will notify Participants of a rejection of a Tender Notice via the DCS Messages facility.",
      cn: "ASX Clear 将通过 DCS 消息功能，将交割通知被拒一事通知参与者。",
      core: "ASX Clear will notify sb of sth",
      points: ["搭配：notify sb of sth", "of 短语：a rejection of …（…被拒）", "方式：via … 通过…"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "ASX Clear will generally notify each Participant by sending a Clearing Message at least once each Business Day.",
      cn: "ASX Clear 通常会在每个营业日至少一次，通过发送清算消息通知每位参与者。",
      core: "ASX Clear will notify each Participant",
      points: ["方式：by + V-ing 通过做…", "频率：generally 通常、at least once each Business Day", "动名词：sending 作 by 的宾语"] },
    { sec: "四、清算 · 保证金 · 担保品",
      en: "ASX Clear will only accept Tender Documentation if it is submitted on a Business Day within the current Delivery Period.",
      cn: "仅当交割文件在当前交割期内的营业日提交时，ASX Clear 才会受理。",
      core: "ASX Clear will only accept … if [条件]",
      points: ["only … if …：仅当…才", "被动：is submitted 被提交", "范围状语：within … 在…期内"] },

    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "Each Market Participant, Adviser and Dealer must ensure their conduct promotes and helps maintain an orderly market.",
      cn: "每位市场参与者、顾问及交易商都必须确保其行为有助于促进并维持有序市场。",
      core: "Each … must ensure [that] their conduct promotes and helps …",
      points: ["宾语从句：ensure (that) …（省略 that）", "并列谓语：promotes and helps maintain", "搭配：help (to) do 有助于做"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "Testing shall be conducted in the manner prescribed by and shall comply with the instructions issued by Nasdaq Baltic.",
      cn: "测试应按 Nasdaq Baltic 规定的方式进行，并遵守其发布的指示。",
      core: "Testing shall be conducted … and shall comply with …",
      points: ["被动：shall be conducted 应被进行", "分词作定语：prescribed by / issued by 由…规定 / 发布的", "两 shall 并列"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "The Trading Member's emergency contact persons must be contactable at all times, and must immediately notify SGX-ST in the event of emergencies.",
      cn: "交易会员的紧急联系人必须始终可联系到，并在发生紧急情况时立即通知 SGX-ST。",
      core: "contact persons must be contactable … and must notify …",
      points: ["be + 形容词：must be contactable 必须可联系", "条件状语：in the event of … 一旦发生…", "两 must 并列谓语"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "Full trading participants, trading participants and foreign participants must ensure that investors under their responsibility comply with all provisions of this article.",
      cn: "完全交易参与者、交易参与者及外国参与者，必须确保其负责的投资者遵守本条全部规定。",
      core: "[三类主语] must ensure that [从句]",
      points: ["三个并列主语共享 must ensure", "后置定语：under their responsibility 其负责的", "搭配：comply with 遵守"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "The risk criteria which will be used and limits which will be applied shall be determined by the Board of Directors.",
      cn: "所采用的风险标准与所适用的限额，应由董事会确定。",
      core: "The criteria … and limits … shall be determined by …",
      points: ["两定语从句：which will be used / which will be applied", "被动 + 施动者：shall be determined by …", "并列主语：criteria and limits"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "Such information must be complete, must not be corrupted and must be legible at the time of receipt by LCH SA.",
      cn: "该等信息在 LCH SA 收到时必须完整、未损坏且清晰可读。",
      core: "information must be complete, must not be corrupted and must be legible",
      points: ["三个 must 并列（be complete / not be corrupted / be legible）", "时间状语：at the time of receipt 在收到时", "施动者：by LCH SA 被…收到"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "Systems should be designed to ensure a high degree of security and operational reliability and should have adequate, scalable capacity.",
      cn: "系统的设计应确保高度的安全性与运行可靠性，并具备充足、可扩展的容量。",
      core: "Systems should be designed … and should have …",
      points: ["被动 + 目的：should be designed to do 应被设计以…", "两 should 并列", "并列形容词：adequate, scalable"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "A CSD should maintain securities in an immobilised or dematerialised form for their transfer by book entry.",
      cn: "中央证券存管机构应以固定化或无纸化形式保管证券，以便通过簿记方式转让。",
      core: "A CSD should maintain securities",
      points: ["方式状语：in a … form 以…形式", "for + 名词表目的：for their transfer 以便转让", "方式：by book entry 通过簿记"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "The FMI should provide clear descriptions of priced services for comparability purposes.",
      cn: "金融市场基础设施应对收费服务提供清晰说明，以便进行比较。",
      core: "The FMI should provide descriptions",
      points: ["情态：should provide 应提供", "of 定语：descriptions of priced services", "目的状语：for … purposes 为…目的"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "SIX x-clear will initiate the necessary measures, and further steps will be defined within the Emergency and Crisis Organization.",
      cn: "SIX x-clear 将启动必要措施，后续步骤将在应急与危机组织框架内确定。",
      core: "SIX will initiate measures, and steps will be defined",
      points: ["and 连接两独立分句（主动 + 被动）", "将来被动：will be defined 将被确定", "范围：within … 在…内"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "The Market may impose such fees and other charges as it may from time to time determine and publish by Circular.",
      cn: "交易所可征收其不时确定并以通函公布的费用及其他收费。",
      core: "The Market may impose such fees and charges as [从句]",
      points: ["such … as …：像…那样的（as 引导定语从句）", "高频状语：from time to time 不时", "并列谓语：determine and publish"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "The Market shall determine and may modify the Trading Hours and Business Days for trading Regulated Derivatives, by disclosure in a Circular.",
      cn: "交易所应以通函披露的方式，确定并可修改受监管衍生品的交易时间与营业日。",
      core: "The Market shall determine and may modify …",
      points: ["不同情态并列：shall determine（应确定）/ may modify（可修改）", "用途：for trading … 为…", "方式：by disclosure in a Circular 以通函披露"] },
    { sec: "五、会员 · 合规 · 风控 · 系统",
      en: "SGX-ST will determine the remuneration of the Manager, which must be paid by the Trading Member.",
      cn: "SGX-ST 将确定管理人的报酬，该报酬须由交易会员支付。",
      core: "SGX-ST will determine the remuneration, which must be paid …",
      points: ["非限制性定语从句：, which … 补充说明 remuneration", "义务 + 被动 + 施动者：must be paid by …", "of 定语：the remuneration of …"] },
    { pat: 0, en: "A Clearing Member must maintain adequate financial resources at all times.", cn: "清算会员必须始终维持充足的财务资源。", core: "A Clearing Member must maintain resources", points: ["情态义务：must maintain 必须维持", "时间状语：at all times 始终"] },
    { pat: 0, en: "Participants may submit orders only during the trading session.", cn: "参与者仅可在交易时段内提交订单。", core: "Participants may submit orders", points: ["许可 + 限制：may … only 仅可", "时间状语：during the trading session"] },
    { pat: 0, en: "The Exchange shall publish the trading calendar before each year.", cn: "交易所应在每年之前公布交易日历。", core: "The Exchange shall publish the calendar", points: ["义务：shall publish 应公布", "时间状语：before each year"] },
    { pat: 0, en: "A Member must not disclose confidential information to any third party.", cn: "会员不得向任何第三方披露机密信息。", core: "A Member must not disclose information", points: ["禁止：must not 不得", "介词短语：to any third party 向第三方"] },
    { pat: 0, en: "Clearing Participants may appoint an agent to act on their behalf.", cn: "清算参与者可委任代理人代其行事。", core: "Participants may appoint an agent", points: ["许可：may appoint 可委任", "不定式作定语：to act on their behalf 代其行事"] },
    { pat: 0, en: "The buyer shall pay the purchase price on the settlement date.", cn: "买方应在交收日支付买入价款。", core: "The buyer shall pay the price", points: ["义务：shall pay 应支付", "时间状语：on the settlement date"] },
    { pat: 0, en: "Members should review their risk controls on a regular basis.", cn: "会员应定期检查其风险控制。", core: "Members should review controls", points: ["建议性义务：should 应当", "状语：on a regular basis 定期"] },
    { pat: 0, en: "No participant may trade for its own account without prior approval.", cn: "未经事先批准，任何参与者不得为自有账户交易。", core: "No participant may trade", points: ["否定 + 许可：No … may 任何…不得", "介词短语：without prior approval 未经批准"] },
    { pat: 0, en: "The Board may delegate any of its powers to a committee.", cn: "董事会可将其任何权力委托给委员会。", core: "The Board may delegate powers", points: ["许可：may delegate 可委托", "方向状语：to a committee"] },
    { pat: 0, en: "A participant must notify the Exchange of any material change.", cn: "参与者必须将任何重大变更通知交易所。", core: "A participant must notify the Exchange of change", points: ["搭配：notify sb of sth 通知某人某事", "义务：must"] },
    { pat: 0, en: "Clearing Members shall meet their obligations when they fall due.", cn: "清算会员应在义务到期时履行义务。", core: "Members shall meet obligations", points: ["义务：shall meet 应履行", "时间从句：when they fall due 到期时"] },
    { pat: 0, en: "Members shall not engage in any form of market manipulation.", cn: "会员不得从事任何形式的市场操纵。", core: "Members shall not engage in manipulation", points: ["禁止：shall not 不得", "搭配：engage in 从事"] },
    { pat: 1, en: "All orders are matched by the trading system according to price-time priority.", cn: "所有订单由交易系统按价格-时间优先撮合。", core: "orders are matched (by the system)", points: ["被动 + 施动者：are matched by", "状语：according to 依照"] },
    { pat: 1, en: "The margin requirement is calculated at the end of each business day.", cn: "保证金要求于每个营业日结束时计算。", core: "requirement is calculated", points: ["一般现在被动：is calculated", "时间状语：at the end of …"] },
    { pat: 1, en: "Failed trades will be reported to the Exchange on the following day.", cn: "交收失败的交易将于次日报告交易所。", core: "trades will be reported", points: ["将来被动：will be reported to", "时间状语：on the following day"] },
    { pat: 1, en: "The collateral must be valued in accordance with the haircut schedule.", cn: "担保品必须依照折扣表估值。", core: "collateral must be valued", points: ["情态 + 被动：must be valued", "状语：in accordance with 依照"] },
    { pat: 1, en: "Positions held by a defaulting member are transferred to a surviving member.", cn: "违约会员持有的头寸转移给存续会员。", core: "positions are transferred", points: ["过去分词作定语：held by … 被…持有的", "被动 + 方向：are transferred to"] },
    { pat: 1, en: "Dividends are credited to the beneficial owner on the payment date.", cn: "股息于付款日入账给实益拥有人。", core: "Dividends are credited", points: ["被动：are credited to 被入账给", "时间状语：on the payment date"] },
    { pat: 1, en: "Any dispute shall be resolved in accordance with the Rules.", cn: "任何争议应依照本规则解决。", core: "dispute shall be resolved", points: ["情态 + 被动：shall be resolved", "状语：in accordance with the Rules"] },
    { pat: 1, en: "Securities are held in book-entry form at the central depository.", cn: "证券以簿记形式存放于中央存管机构。", core: "Securities are held", points: ["被动 + 方式：are held in … form", "地点状语：at the central depository"] },
    { pat: 1, en: "The transaction is recorded in the participant's account immediately.", cn: "交易即时记入参与者账户。", core: "transaction is recorded", points: ["被动 + 地点：is recorded in", "时间副词：immediately"] },
    { pat: 1, en: "All records must be retained for the prescribed period.", cn: "所有记录必须保存规定的期限。", core: "records must be retained", points: ["情态 + 被动：must be retained", "时长状语：for the prescribed period"] },
    { pat: 2, en: "If a member fails to deliver, the clearing house may execute a buy-in.", cn: "若会员未能交付，清算所可执行强制买入。", core: "If [条件], the house may execute a buy-in", points: ["条件从句：If … fails to", "主句许可：may execute"] },
    { pat: 2, en: "Where the collateral is insufficient, the member shall post additional cover.", cn: "在担保品不足的情形下，会员应追加担保。", core: "Where [条件], the member shall post cover", points: ["Where ≈ if 在…情形下", "义务：shall post 应追加"] },
    { pat: 2, en: "Unless otherwise agreed, settlement takes place on a T+2 basis.", cn: "除非另有约定，交收按 T+2 进行。", core: "Unless [条件], settlement takes place", points: ["Unless otherwise agreed 除非另有约定", "on a … basis 以…方式"] },
    { pat: 2, en: "Provided that the conditions are met, the application will be approved.", cn: "前提是满足相关条件，该申请将获批准。", core: "Provided that [条件], the application will be approved", points: ["Provided that 前提是", "将来被动：will be approved"] },
    { pat: 2, en: "If the price exceeds the limit, the order will be rejected automatically.", cn: "若价格超过限制，订单将被自动拒绝。", core: "If [条件], the order will be rejected", points: ["条件从句：If … exceeds", "将来被动：will be rejected"] },
    { pat: 2, en: "Where a default occurs, the default fund may be applied to cover losses.", cn: "在发生违约的情形下，违约基金可用于弥补损失。", core: "Where [条件], the fund may be applied", points: ["条件从句：Where a default occurs", "许可 + 被动 + 目的：may be applied to cover"] },
    { pat: 2, en: "Should the system fail, trading will be suspended until further notice.", cn: "万一系统故障，交易将暂停直至另行通知。", core: "Should [条件], trading will be suspended", points: ["Should + 倒装：万一…（= if）", "until further notice 直至另行通知"] },
    { pat: 2, en: "Unless the context otherwise requires, terms have the meanings defined below.", cn: "除非上下文另有要求，术语具有下文所定义的含义。", core: "Unless [条件], terms have the meanings", points: ["法规固定条件句：Unless the context otherwise requires", "过去分词作定语：defined below"] },
    { pat: 2, en: "If a participant becomes insolvent, its access will be terminated.", cn: "若参与者资不抵债，其接入将被终止。", core: "If [条件], access will be terminated", points: ["条件从句：If … becomes insolvent", "将来被动：will be terminated"] },
    { pat: 2, en: "Where two orders have the same price, time priority applies.", cn: "在两笔订单价格相同的情形下，适用时间优先。", core: "Where [条件], time priority applies", points: ["Where 在…情形下", "applies 适用（不及物）"] },
    { pat: 2, en: "If no theoretical price is formed, the auction is cancelled.", cn: "若未形成理论价格，则取消该集合竞价。", core: "If [条件], the auction is cancelled", points: ["条件从句（被动）：If no … is formed", "被动：is cancelled"] },
    { pat: 3, en: "A member which breaches the Rules may be subject to disciplinary action.", cn: "违反本规则的会员可能受到纪律处分。", core: "A member … may be subject to action", points: ["定语从句：which breaches … 修饰 member", "搭配：be subject to 可能受到"] },
    { pat: 3, en: "The account into which the funds are paid must be a segregated account.", cn: "资金存入的账户必须是隔离账户。", core: "The account … must be a segregated account", points: ["介词 + 关系代词：into which … 定语从句", "情态 + 系表：must be"] },
    { pat: 3, en: "Securities that are not eligible cannot be settled through the system.", cn: "不合资格的证券不能通过系统交收。", core: "Securities … cannot be settled", points: ["定语从句：that are not eligible", "情态否定 + 被动：cannot be settled"] },
    { pat: 3, en: "The clearing member who assumes the obligation becomes the counterparty.", cn: "承担该义务的清算会员成为对手方。", core: "The member … becomes the counterparty", points: ["定语从句：who assumes … 修饰 member", "系动词：becomes"] },
    { pat: 3, en: "Any information which is provided must be accurate and complete.", cn: "所提供的任何信息必须准确且完整。", core: "information … must be accurate and complete", points: ["定语从句（被动）：which is provided", "情态 + 并列表语：must be … and …"] },
    { pat: 3, en: "The date on which the transfer takes effect is the settlement date.", cn: "转移生效之日即为交收日。", core: "The date … is the settlement date", points: ["介词 + 关系代词：on which … 定语从句", "搭配：takes effect 生效"] },
    { pat: 3, en: "A participant whose membership is suspended cannot enter new orders.", cn: "会籍被暂停的参与者不能录入新订单。", core: "A participant … cannot enter orders", points: ["whose 引导定语从句：whose membership is suspended", "情态否定：cannot enter"] },
    { pat: 3, en: "The fees that the Exchange charges are published in a circular.", cn: "交易所收取的费用以通函公布。", core: "The fees … are published", points: ["定语从句（宾语关系）：that the Exchange charges", "被动：are published"] },
    { pat: 3, en: "The rules that govern settlement are set out in Chapter 5.", cn: "规范交收的规则载于第 5 章。", core: "The rules … are set out", points: ["定语从句：that govern settlement", "被动 + 地点：are set out in"] },
    { pat: 3, en: "A person who is not a member may not access the system.", cn: "非会员不得接入系统。", core: "A person … may not access the system", points: ["定语从句：who is not a member", "禁止：may not"] },
    { pat: 3, en: "The member that submits the order bears responsibility for it.", cn: "提交订单的会员对其负责。", core: "The member … bears responsibility", points: ["定语从句：that submits the order", "搭配：bear responsibility for 对…负责"] },
    { pat: 4, en: "The Exchange requires each member to appoint a compliance officer.", cn: "交易所要求每位会员委任一名合规主任。", core: "The Exchange requires member to appoint", points: ["使役：require sb to do 要求某人做", "宾语：each member"] },
    { pat: 4, en: "The system enables participants to submit orders electronically.", cn: "该系统使参与者能以电子方式提交订单。", core: "The system enables participants to submit", points: ["使役：enable sb to do 使某人能做", "方式副词：electronically"] },
    { pat: 4, en: "A default may cause the clearing house to invoke its default procedures.", cn: "违约可能促使清算所启动其违约程序。", core: "A default may cause the house to invoke", points: ["使役：cause sb/sth to do 促使…做", "许可：may"] },
    { pat: 4, en: "The Rules require that all trades be reported within fifteen minutes.", cn: "规则要求所有交易在十五分钟内报告。", core: "The Rules require that all trades be reported", points: ["require that … be：要求（虚拟语气，动词原形 be）", "时间状语：within fifteen minutes"] },
    { pat: 4, en: "The Exchange may direct a member to close out its open positions.", cn: "交易所可指令会员平掉其未平仓头寸。", core: "The Exchange may direct member to close out", points: ["使役：direct sb to do 指令某人做", "搭配：close out 平仓"] },
    { pat: 4, en: "Regulations require members to keep records for seven years.", cn: "法规要求会员保存记录七年。", core: "Regulations require members to keep records", points: ["使役：require sb to do", "时长状语：for seven years"] },
    { pat: 4, en: "The clearing house allows members to substitute eligible collateral.", cn: "清算所允许会员替换合资格担保品。", core: "The house allows members to substitute", points: ["使役：allow sb to do 允许某人做", "宾语：eligible collateral"] },
    { pat: 4, en: "Failure to pay will cause the position to be liquidated.", cn: "未付款将导致头寸被平仓。", core: "Failure … will cause the position to be liquidated", points: ["名词化主语：Failure to do 未能做", "使役 + 被动：cause sth to be done"] },
    { pat: 4, en: "The Exchange may require a member to provide additional information.", cn: "交易所可要求会员提供额外信息。", core: "The Exchange may require member to provide", points: ["使役：require sb to do", "宾语：additional information"] },
    { pat: 4, en: "The rules permit a member to appoint a settlement agent.", cn: "规则允许会员委任结算代理。", core: "rules permit a member to appoint", points: ["使役：permit sb to do 允许某人做", "宾语：a settlement agent"] },
    { pat: 4, en: "The system forces the member to confirm before submission.", cn: "系统在提交前强制会员确认。", core: "The system forces the member to confirm", points: ["使役：force sb to do 强制某人做", "时间状语：before submission"] },
    { pat: 5, en: "Obligations arising out of market contracts are settled through the clearing house.", cn: "由市场合约产生的义务通过清算所交收。", core: "Obligations … are settled", points: ["现在分词作定语：arising out of … 由…产生的", "被动 + 方式：are settled through"] },
    { pat: 5, en: "The member responsible for settlement must ensure sufficient funds.", cn: "负责交收的会员必须确保资金充足。", core: "The member … must ensure funds", points: ["形容词短语后置修饰：responsible for …", "情态 + 及物：must ensure"] },
    { pat: 5, en: "Securities eligible for settlement are listed in the appendix.", cn: "合资格交收的证券列于附录。", core: "Securities … are listed", points: ["形容词短语后置修饰：eligible for …", "被动 + 地点：are listed in"] },
    { pat: 5, en: "The amount payable by the member is shown on the settlement statement.", cn: "会员应付的金额显示于交收单上。", core: "The amount … is shown", points: ["形容词后置修饰：payable by … 应付的", "被动 + 地点：is shown on"] },
    { pat: 5, en: "Any notice given under this Rule takes effect upon receipt.", cn: "依本规则发出的任何通知于收到时生效。", core: "Any notice … takes effect", points: ["过去分词作定语：given under this Rule", "介词短语：upon receipt 收到时"] },
    { pat: 5, en: "The procedures set out below apply to all clearing participants.", cn: "下文列出的程序适用于所有清算参与者。", core: "The procedures … apply to participants", points: ["过去分词后置修饰：set out below", "搭配：apply to 适用于"] },
    { pat: 5, en: "A member acting as an agent must disclose its capacity.", cn: "作为代理人行事的会员必须披露其身份。", core: "A member … must disclose its capacity", points: ["现在分词作定语：acting as …", "情态 + 及物：must disclose"] },
    { pat: 5, en: "Instructions received after the cut-off time will be processed the next day.", cn: "截止时间后收到的指令将于次日处理。", core: "Instructions … will be processed", points: ["过去分词后置修饰：received after …", "将来被动：will be processed"] },
    { pat: 5, en: "The party in default shall bear the costs arising therefrom.", cn: "违约方应承担由此产生的费用。", core: "The party … shall bear the costs", points: ["介词短语后置修饰：in default 违约的", "分词短语：arising therefrom 由此产生的"] },
    { pat: 5, en: "Any securities delivered late are subject to a penalty.", cn: "任何迟延交付的证券须缴纳罚金。", core: "securities … are subject to a penalty", points: ["过去分词后置修饰：delivered late", "搭配：be subject to 须承受"] },
    { pat: 5, en: "The fees specified in the schedule are payable monthly.", cn: "附表规定的费用按月支付。", core: "The fees … are payable monthly", points: ["过去分词后置修饰：specified in the schedule", "表语：payable monthly 应按月支付"] },
    { pat: 6, en: "Members may amend, cancel or replace an order before it is executed.", cn: "会员可在订单成交前修改、撤销或替换订单。", core: "Members may amend, cancel or replace an order", points: ["并列动词：amend, cancel or replace", "时间从句：before it is executed"] },
    { pat: 6, en: "The clearing house collects margin and monitors exposure continuously.", cn: "清算所持续收取保证金并监控敞口。", core: "The house collects margin and monitors exposure", points: ["并列谓语：collects … and monitors", "副词：continuously"] },
    { pat: 6, en: "Each participant is responsible for its own trades and those of its clients.", cn: "每位参与者对自身及其客户的交易负责。", core: "Each participant is responsible for A and B", points: ["并列宾语：A and B", "替代词：those of … 指 trades"] },
    { pat: 6, en: "The Exchange may impose fines, suspend membership or expel a member.", cn: "交易所可处以罚款、暂停会籍或开除会员。", core: "The Exchange may impose …, suspend … or expel …", points: ["三并列谓语共享 may", "or 择一"] },
    { pat: 6, en: "Trades are cleared, netted and settled on a daily basis.", cn: "交易按日清算、轧差并交收。", core: "Trades are cleared, netted and settled", points: ["并列过去分词（被动）：cleared, netted and settled", "状语：on a daily basis 按日"] },
    { pat: 6, en: "A member must be solvent, competent and of good standing.", cn: "会员必须有偿付能力、能胜任且信誉良好。", core: "A member must be solvent, competent and of good standing", points: ["三并列表语", "介词短语作表语：of good standing 信誉良好"] },
    { pat: 6, en: "The report shall include the price, quantity and time of each trade.", cn: "报告应载明每笔交易的价格、数量与时间。", core: "The report shall include price, quantity and time", points: ["并列宾语：price, quantity and time", "of 短语作定语：of each trade"] },
    { pat: 6, en: "Clearing members contribute to and benefit from the default fund.", cn: "清算会员向违约基金出资并从中受益。", core: "members contribute to and benefit from the fund", points: ["并列动词短语共享宾语：contribute to and benefit from", "共享宾语：the default fund"] },
    { pat: 6, en: "The Exchange sets, monitors and enforces the trading rules.", cn: "交易所制定、监督并执行交易规则。", core: "The Exchange sets, monitors and enforces the rules", points: ["三并列谓语", "共享宾语：the trading rules"] },
    { pat: 6, en: "A member may act as principal or as agent.", cn: "会员可作为自营方或代理方行事。", core: "A member may act as principal or as agent", points: ["并列介词短语：as A or as B", "许可：may act"] },
    { pat: 6, en: "The depository receives, holds and delivers securities on instruction.", cn: "存管机构按指示接收、保管并交付证券。", core: "The depository receives, holds and delivers securities", points: ["三并列谓语", "状语：on instruction 按指示"] },
    { pat: 7, en: "The trading system automatically rejects orders that breach price limits.", cn: "交易系统自动拒绝超出价格限制的订单。", core: "The system rejects orders", points: ["无生命主语 + 现在时：客观规则", "定语从句：that breach …"] },
    { pat: 7, en: "The clearing house guarantees the settlement of every registered trade.", cn: "清算所保证每笔已登记交易的交收。", core: "The house guarantees the settlement", points: ["机构作主语：guarantees", "of 短语作定语：of every registered trade"] },
    { pat: 7, en: "The depository maintains the securities accounts of all participants.", cn: "存管机构维护所有参与者的证券账户。", core: "The depository maintains the accounts", points: ["机构主语 + 现在时", "of 短语作定语：of all participants"] },
    { pat: 7, en: "The Exchange will disclose any change by way of a circular.", cn: "交易所将以通函方式披露任何变更。", core: "The Exchange will disclose any change", points: ["机构主语 + will", "介词短语：by way of 以…方式"] },
    { pat: 7, en: "The System records the time at which each order is received.", cn: "系统记录每笔订单被接收的时间。", core: "The System records the time", points: ["系统主语 + 现在时", "介词 + 关系代词：at which … 定语从句"] },
    { pat: 7, en: "CDP acts as the central counterparty to all cleared trades.", cn: "CDP 作为所有已清算交易的中央对手方。", core: "CDP acts as the counterparty", points: ["机构主语 + acts as", "介词短语作定语：to all cleared trades"] },
    { pat: 7, en: "The clearing house may close out the positions of a defaulting member.", cn: "清算所可平掉违约会员的头寸。", core: "The house may close out the positions", points: ["机构主语 + may", "of 短语：of a defaulting member（分词作定语）"] },
    { pat: 7, en: "The Exchange operates a continuous trading session on each business day.", cn: "交易所在每个营业日运行连续交易时段。", core: "The Exchange operates a session", points: ["机构主语 + 现在时", "时间状语：on each business day"] },
    { pat: 7, en: "The clearing system calculates each member's net position daily.", cn: "清算系统每日计算每位会员的净头寸。", core: "The system calculates the net position", points: ["系统主语 + 现在时", "频率副词：daily"] },
    { pat: 7, en: "The Exchange determines the reference price for each security.", cn: "交易所为每只证券确定参考价。", core: "The Exchange determines the reference price", points: ["机构主语 + 现在时", "介词短语作定语：for each security"] },
    { pat: 7, en: "The clearing house publishes its margin parameters on its website.", cn: "清算所在其网站公布保证金参数。", core: "The house publishes its parameters", points: ["机构主语 + 现在时", "地点状语：on its website"] },
    { pat: 1, en: "An order that is not fully executed may be cancelled at the end of the auction.", cn: "未全部成交的订单可在集合竞价结束时被取消。", core: "An order … may be cancelled", points: ["定语从句：that is not fully executed", "情态 + 被动：may be cancelled"] },
    { pat: 4, en: "The Rules require every participant to segregate client assets from its own.", cn: "规则要求每位参与者将客户资产与自有资产隔离。", core: "The Rules require participant to segregate", points: ["使役：require sb to do", "搭配：segregate A from B 将A与B隔离"] }
  ],
  // 每句"最突出的句式"索引（对应 patterns），-1 表示无单一突出结构、不纳入句型识别题
  patternOf: [
    1, -1, 3, 5, 1, -1, 6, -1, -1, 3,
    6, 2, 3, 2, 2, 3, 3, 6, -1, 2,
    2, -1, 4, -1, 4, -1, 6, 2, 2, 2,
    2, 3, 6, -1, 3, 2, 4, 2, 4, 4,
    5, 3, 3, 6, 3, -1, -1, 2, 6, 1,
    6, -1, 3, 6, 6, 5, -1, 6, 3, 6,
    3
  ]
};
